import Pkg

const PROJECT_DIRECTORY = normpath(joinpath(@__DIR__, ".."))
Pkg.activate(PROJECT_DIRECTORY)

using Pluto

include(joinpath(PROJECT_DIRECTORY, "src", "FigureRegistry.jl"))

const MASTER_NOTEBOOK =
    joinpath(PROJECT_DIRECTORY, "dynamo_diagnostics.jl")
const OUTPUT_PATH =
    joinpath(PROJECT_DIRECTORY, "src", "BatchCellIndex.jl")
const REQUIRED_SETUP_CELL_IDS = Set([
    Base.UUID("34d6b5f4-9c2d-42d5-9034-543aeb8ae151"),
    Base.UUID("8f1f1d9a-e6df-4dd1-b5b3-2d2c52c86686"),
])

function source_checksum(path)
    checksum = UInt64(0xcbf29ce484222325)
    for byte in read(path)
        checksum = (checksum ⊻ UInt64(byte)) * UInt64(0x100000001b3)
    end
    string(checksum; base = 16, pad = 16)
end

function dependency_closure(topology, seed_cells)
    selected = Set(seed_cells)
    pending = collect(seed_cells)
    while !isempty(pending)
        cell = pop!(pending)
        references = topology.nodes[cell].references
        for upstream in Pluto.where_assigned(topology, references)
            if upstream ∉ selected
                push!(selected, upstream)
                push!(pending, upstream)
            end
        end
    end
    selected
end

function write_uuid_vector(io, name, ids)
    println(io, "const ", name, " = Base.UUID[")
    for id in ids
        println(io, "    Base.UUID(\"", id, "\"),")
    end
    println(io, "]\n")
end

source = Pluto.load_notebook_nobackup(MASTER_NOTEBOOK)
source.topology =
    Pluto.updated_topology(source.topology, source, source.cells)
execution_order = collect(Pluto.topological_order(source.topology))
isempty(Pluto.topological_order(source.topology).errable) ||
    error("The master notebook has dependency errors.")

figure_cells = Dict{String,Vector{Base.UUID}}()
for (name, symbol) in FIGURE_REGISTRY
    seeds = collect(Pluto.where_assigned(source.topology, Set([symbol])))
    isempty(seeds) && error("No cell assigns $symbol for figure $name.")
    selected = dependency_closure(source.topology, seeds)
    for cell in source.cells
        cell.cell_id in REQUIRED_SETUP_CELL_IDS && push!(selected, cell)
    end
    figure_cells[name] =
        [cell.cell_id for cell in execution_order if cell in selected]
end

open(OUTPUT_PATH, "w") do io
    println(io, "# This file is generated by tools/generate_batch_index.jl.")
    println(io, "# Do not edit it manually.\n")
    println(
        io,
        "const MASTER_SOURCE_CHECKSUM = \"",
        source_checksum(MASTER_NOTEBOOK),
        "\"\n",
    )
    write_uuid_vector(
        io,
        "CELL_EXECUTION_ORDER",
        getproperty.(execution_order, :cell_id),
    )
    println(io, "const FIGURE_CELL_IDS = Dict{String,Set{Base.UUID}}(")
    for name in sort(collect(keys(figure_cells)))
        println(io, "    ", repr(name), " => Set(Base.UUID[")
        for id in figure_cells[name]
            println(io, "        Base.UUID(\"", id, "\"),")
        end
        println(io, "    ]),")
    end
    println(io, ")")
end

println("Batch dependency index written to: ", OUTPUT_PATH)
println("Master checksum: ", source_checksum(MASTER_NOTEBOOK))
println("Indexed figures: ", length(figure_cells))
println("Indexed cells: ", length(execution_order))
